/*!***************************************************
* Dictionary Auto Correction,
* Script Ver 1.4
* http://www.expoodisha.com
* Copyright (c) 2018, Manas Ranjan Swain

*****************************************************/

$(document).ready(function() {
    $('#fnrbtn').click(function() {
    var textarea=$('#uInput');
textarea.val(textarea.val().replace(/ପଡି/g,"ପଡ଼ି"));
textarea.val(textarea.val().replace(/ଳାଗି/g,"ଲାଗି"));
textarea.val(textarea.val().replace(/ଢ଼ାଳି/g,"ଢାଳି"));
textarea.val(textarea.val().replace(/ଗୋଡ/g,"ଗୋଡ଼"));
textarea.val(textarea.val().replace(/ଗୁଡି/g,"ଗୁଡ଼ି"));
textarea.val(textarea.val().replace(/ବିଡି/g,"ବିଡ଼ି"));
textarea.val(textarea.val().replace(/ଏକ୍‌ସ୍‌ଚେଞ୍ଜ୍‌/g,"ଏକ୍ସଚେଞ୍ଜ"));
textarea.val(textarea.val().replace(/ଚେକ/g,"ଚେକ୍‌"));
textarea.val(textarea.val().replace(/ଭଡା/g,"ଭଡ଼ା"));
textarea.val(textarea.val().replace(/ବ୍ରିଟିଶ୍‌/g,"ବ୍ରିଟିଶ"));
textarea.val(textarea.val().replace(/କବଜା/g,"କବ୍‌ଜା"));
textarea.val(textarea.val().replace(/ଆନ୍ଦନ/g,"ଆନନ୍ଦ"));
textarea.val(textarea.val().replace(/ଗଡ/g,"ଗଡ଼"));
textarea.val(textarea.val().replace(/ଇନ୍‌୍‌ସ୍ୟୁରେନ୍ସ/g,"ଇନ୍‌ସ୍ୟୁରାନ୍ସ"));
textarea.val(textarea.val().replace(/ସ୍କୋୟାର/g,"ସ୍କୋୟାର"));
textarea.val(textarea.val().replace(/ସମ‌େ‌ସ୍ତ/g,"ସମସ୍ତେ"));
textarea.val(textarea.val().replace(/ଦୃଢ଼଼/g,"ଦୃଢ଼"));
textarea.val(textarea.val().replace(/ଦୃଢ/g,"ଦୃଢ଼"));
textarea.val(textarea.val().replace(/ଦୌଡାଦୌଡି/g,"ଦୌଡ଼ାଦୌଡ଼ି"));
textarea.val(textarea.val().replace(/ଈଷାନ/g,"ଈଶାନ"));
textarea.val(textarea.val().replace(/ଖଡି/g,"ଖଡ଼ି"));
textarea.val(textarea.val().replace(/ଢ଼ଙ୍ଗ/g,"ଢଙ୍ଗ"));
textarea.val(textarea.val().replace(/ବଲବ/g,"ବଲ୍‌ବ"));
textarea.val(textarea.val().replace(/ଢ଼ାଞ୍ଚା/g,"ଢାଞ୍ଚା"));
textarea.val(textarea.val().replace(/ଆଇନ/g,"ଆଇନ୍‌"));
textarea.val(textarea.val().replace(/କନ୍‌ଷ୍ଟେବଲ/g,"କନଷ୍ଟେବଳ"));
textarea.val(textarea.val().replace(/ଲଣ୍ଡନ୍‌/g,"ଲଣ୍ଡନ"));
textarea.val(textarea.val().replace(/ପ୍ରତ୍ୟାର୍ପଣ/g,"ପ୍ରତ୍ୟର୍ପଣ"));
textarea.val(textarea.val().replace(/ପାଶ୍ୱର୍ରେ/g,"ପାର୍ଶ୍ବରେ"));
textarea.val(textarea.val().replace(/ପରୀକ୍ଷାଣ/g,"ପରୀକ୍ଷଣ"));
textarea.val(textarea.val().replace(/ପକାତା/g,"ପତାକା"));
textarea.val(textarea.val().replace(/ପକତା/g,"ପତାକା"));
textarea.val(textarea.val().replace(/କଡାକଡି/g,"କଡ଼ାକଡ଼ି"));
textarea.val(textarea.val().replace(/ବେଳେକୁ/g,"ବେଳକୁ"));
textarea.val(textarea.val().replace(/ୱାର୍ଡ/g,"ୱାର୍ଡ଼"));
textarea.val(textarea.val().replace(/ଉଣା/g,"ଊଣା"));
textarea.val(textarea.val().replace(/ଓଡିଶା/g,"ଓଡ଼ିଶା"));
textarea.val(textarea.val().replace(/କନେଷ୍ଟବଲ/g,"କନଷ୍ଟେବଳ"));
textarea.val(textarea.val().replace(/ସାମନା/g,"ସାମ୍‌ନା"));
textarea.val(textarea.val().replace(/ମଲଟି/g,"ମଲ୍‌ଟି"));
textarea.val(textarea.val().replace(/ପେଡି/g,"ପେଡ଼ି"));
textarea.val(textarea.val().replace(/ସାହାର୍ଯ୍ୟ/g,"ସାହାଯ୍ୟ"));
textarea.val(textarea.val().replace(/ଦୌଡି/g,"ଦୌଡ଼ି"));
textarea.val(textarea.val().replace(/ଢ଼ାଲ/g,"ଢାଲ"));
textarea.val(textarea.val().replace(/ଭେକିଲସ୍‌/g,"ଭେଇକିଲ୍ସ "));
textarea.val(textarea.val().replace(/ବିଡ଼ିଏ/g,"ବିଡିଏ"));
textarea.val(textarea.val().replace(/ଦେଢ/g,"ଦେଢ଼"));
textarea.val(textarea.val().replace(/ସୁରାଟ/g,"ସୁରଟ"));
textarea.val(textarea.val().replace(/କିକ୍ରେଟ/g,"କ୍ରିକେଟ"));
textarea.val(textarea.val().replace(/ ଦେଇଥୀିଲେ/g,"ଦେଇଥିଲେ"));
textarea.val(textarea.val().replace(/କ୍ଷୀରାଦ/g,"କ୍ଷୀରୋଦ"));
textarea.val(textarea.val().replace(/ପଛ‌େର/g,"ପଛରେ"));
textarea.val(textarea.val().replace(/ଜଂଘ/g,"ଜଙ୍ଘ"));
textarea.val(textarea.val().replace(/ହାଇେଓ୍ଵ/g,"ହାଇୱେ"));
textarea.val(textarea.val().replace(/ଫୋଙ୍ଗସ/g,"ଫଙ୍ଗସ୍‌"));
textarea.val(textarea.val().replace(/ସରାକରୀ/g,"ସରକାରୀ"));
textarea.val(textarea.val().replace(/ସରାକାରୀ/g,"ସରକାରୀ"));
textarea.val(textarea.val().replace(/ଦୁରାରୋଗ୍ୟରେ/g,"ଦୁରାରୋଗରେ"));
textarea.val(textarea.val().replace(/ଏଡ଼୍‍ସ/g,"ଏଡ୍‌ସ"));
textarea.val(textarea.val().replace(/ପହଞ୍ଚିି/g,"ପହଞ୍ଚି"));
textarea.val(textarea.val().replace(/ଡ଼ାଭିଡ଼୍‍ସନ/g," ଡାଭିଡ୍‌ସନ"));
textarea.val(textarea.val().replace(/ବସ୍‍ଷ୍ଟାଣ୍ଡ୍‍/g," ବସ୍‌ଷ୍ଟାଣ୍ଡ"));
textarea.val(textarea.val().replace(/ଅଟୋଷ୍ଟାଣ୍ଡ୍‍/g," ଅଟୋଷ୍ଟାଣ୍ଡ"));
textarea.val(textarea.val().replace(/କାମୁଡି/g,"କାମୁଡ଼ି"));
textarea.val(textarea.val().replace(/ପୋଡି/g,"ପୋଡ଼ି"));
textarea.val(textarea.val().replace(/ମାଡ/g,"ମାଡ଼"));
textarea.val(textarea.val().replace(/ପାଢୀ/g,"ପାଢ଼ୀ"));
textarea.val(textarea.val().replace(/ଚଢଉ/g,"ଚଢ଼ଉ"));
textarea.val(textarea.val().replace(/ଭିଡ/g,"ଭିଡ଼"));
textarea.val(textarea.val().replace(/ପୋଡା/g,"ପୋଡ଼ା"));
textarea.val(textarea.val().replace(/ଖାଳରେ/g,"ଖାଲରେ"));
textarea.val(textarea.val().replace(/ଲଢି/g,"ଲଢ଼ି"));
textarea.val(textarea.val().replace(/ଉପନ୍ଦ୍ରେ/g,"ଉପେନ୍ଦ୍ର"));
textarea.val(textarea.val().replace(/ପଏଣ୍ଟ୍‌/g," ପଏଣ୍ଟ"));
textarea.val(textarea.val().replace(/ଏୟାର୍‌/g,"ଏୟାର"));
textarea.val(textarea.val().replace(/ଅସଦାଚାରଣ/g," ଅସଦାଚରଣ "));
textarea.val(textarea.val().replace(/ ସବ୍‍ଜେକ୍ଟିଭ/g," ସବ୍‌ଜକ୍ଟିଭ "));
textarea.val(textarea.val().replace(/ଅବଜେକ୍ଟିଭ୍‍ /g,"ଅବ୍‌ଜେକ୍‌ଟିଭ "));
textarea.val(textarea.val().replace(/ଅବଜେକ୍ଟିଭ୍‍ରେ/g,"ଅବ୍‌ଜେକ୍‌ଟିଭରେ  "));
textarea.val(textarea.val().replace(/ମଲ୍‍ଟିପ୍‍ଲ୍‍/g,"ମଲ୍‌ଟିପଲ "));
textarea.val(textarea.val().replace(/ଓଏଏସ୍‌/g,"ଓଏଏସ"));
textarea.val(textarea.val().replace(/ଏକାଡ଼େମୀ/g,"ଏକାଡେମୀ"));
textarea.val(textarea.val().replace(/ଏକାଡ଼େମି/g,"ଏକାଡେମି"));
textarea.val(textarea.val().replace(/ଆରଏସଏସ/g,"ଆରଏସ୍‌ଏସ"));
textarea.val(textarea.val().replace(/ପୃଷ୍ଟା/g,"ପୃଷ୍ଠା"));
textarea.val(textarea.val().replace(/ଅତ୍ୟାଧିକ/g,"ଅତ୍ୟଧିକ"));
textarea.val(textarea.val().replace(/ସିର୍ଦ୍ଧାଥ/g,"ସିଦ୍ଧାର୍ଥ"));
textarea.val(textarea.val().replace(/ର୍‌/g,"ର"));
textarea.val(textarea.val().replace(/ସିଲଂ/g,"ଶିଲଂ"));
textarea.val(textarea.val().replace(/ଚମ୍ପିଆନ୍‌/g,"ଚମ୍ପିଆନ"));
textarea.val(textarea.val().replace(/ଚମ୍ପିଆନ୍‍/g,"ଚମ୍ପିଆନ"));
textarea.val(textarea.val().replace(/ଡ଼ାକଘର/g,"ଡାକଘର"));
textarea.val(textarea.val().replace(/ଡ଼ାକର/g,"ଡାକର"));
textarea.val(textarea.val().replace(/କନେଷ୍ଟବଳ/g,"କନଷ୍ଟେବଳ"));
textarea.val(textarea.val().replace(/ଟ୍ରାଫିକ/g,"ଟ୍ରାଫିକ୍‌"));
textarea.val(textarea.val().replace(/କାଢି/g,"କାଢ଼ି"));
textarea.val(textarea.val().replace(/ଳଢ଼ୁଆ/g,"ଲଢ଼ୁଆ"));
textarea.val(textarea.val().replace(/ଦୂରେରେ/g,"ଦୂରରେ"));
textarea.val(textarea.val().replace(/ହଳଦର/g,"ହଳଧର"));
textarea.val(textarea.val().replace(/ପାଂପଡ/g,"ପାଂପଡ଼"));
textarea.val(textarea.val().replace(/କୃତି୍ରମ/g,"କୃତ୍ରିମ"));
textarea.val(textarea.val().replace(/ପୋଷ୍ଟ୍‍/g,"ପୋଷ୍ଟ"));
textarea.val(textarea.val().replace(/ପୋଷ୍ଟ୍‌/g,"ପୋଷ୍ଟ"));
textarea.val(textarea.val().replace(/କାମୁଡା/g,"କାମୁଡ଼ା"));
textarea.val(textarea.val().replace(/ଭାରତନାଟ୍ୟମ୍‍/g,"ଭାରତନାଟ୍ୟମ"));
textarea.val(textarea.val().replace(/ଭାରତନାଟ୍ୟମ୍‌/g,"ଭାରତନାଟ୍ୟମ"));
textarea.val(textarea.val().replace(/ଭରତନାଟ୍ୟମ୍‌/g,"ଭାରତନାଟ୍ୟମ"));
textarea.val(textarea.val().replace(/ଭରତନାଟ୍ୟମ/g,"ଭାରତନାଟ୍ୟମ"));
textarea.val(textarea.val().replace(/କୁଢ/g,"କୁଢ଼"));
textarea.val(textarea.val().replace(/ଭାଂଗି/g,"ଭାଙ୍ଗି"));
textarea.val(textarea.val().replace(/ସେକେଣ୍ଡ/g," ସେକେଣ୍ଡ"));
textarea.val(textarea.val().replace(/ସେମି/g," ସେମି"));
textarea.val(textarea.val().replace(/ଟଙ୍କା/g," ଟଙ୍କା"));
textarea.val(textarea.val().replace(/ରେକର୍ଡ/g,"ରେକର୍ଡ଼"));
textarea.val(textarea.val().replace(/ଗୁଡ/g,"ଗୁଡ଼"));
textarea.val(textarea.val().replace(/ବାଡି/g,"ବାଡ଼ି"));
textarea.val(textarea.val().replace(/ଭଡା/g,"ଭଡ଼ା"));
textarea.val(textarea.val().replace(/ଭଡ଼ା/g,"ଭଡ଼ା"));
textarea.val(textarea.val().replace(/ଗାର୍ଡ/g,"ଗାର୍ଡ଼"));
textarea.val(textarea.val().replace(/ଭିଷା/g,"ଭିସା"));
textarea.val(textarea.val().replace(/ଭିଶା/g,"ଭିସା"));
textarea.val(textarea.val().replace(/ଷ୍ଟାଡିୟମ/g,"ଷ୍ଟାଡିୟମ୍‌"));
textarea.val(textarea.val().replace(/ଷ୍ଟାଡିୟମ/g,"ଷ୍ଟାଡିୟମ୍‌"));
textarea.val(textarea.val().replace(/ପଡି/g,"ପଡ଼ି"));
textarea.val(textarea.val().replace(/ପୁଡି/g,"ପୁଡ଼ି"));
textarea.val(textarea.val().replace(/ସାମସଙ୍ଗ୍‌/g,"ସାମ୍‌ସଙ୍ଗ"));
textarea.val(textarea.val().replace(/ସମ୍ପଦ୍ରାୟ/g,"ସମ୍ପ୍ରଦାୟ"));
textarea.val(textarea.val().replace(/ବଢୁ/g,"ବଢ଼ୁ"));
textarea.val(textarea.val().replace(/ଗାଡି/g,"ଗାଡ଼ି"));
textarea.val(textarea.val().replace(/କମ୍ପ୍ୟୁଟର/g,"କଂପ୍ୟୁଟର"));
textarea.val(textarea.val().replace(/ଢ଼ିଲା/g,"ଢିଲା"));
textarea.val(textarea.val().replace(/ଳଗାଇ/g,"ଲଗାଇ"));
textarea.val(textarea.val().replace(/ରେଜିଷ୍ଟାର/g,"ରେଜିଷ୍ଟ୍ରାର"));
textarea.val(textarea.val().replace(/ଡ଼େଟ/g,"ଡେଟ୍‌"));
textarea.val(textarea.val().replace(/ସବଡ଼ିଭିଜନ୍ /g,"ସବଡିଭିଜନ୍‍ "));
textarea.val(textarea.val().replace(/ଲକ୍ଷ/g," ଲକ୍ଷ"));
textarea.val(textarea.val().replace(/କିମି/g," କିମି"));
textarea.val(textarea.val().replace(/କନ୍‌ଷ୍ଟବଲ୍/g,"କନଷ୍ଟେବଳ"));
textarea.val(textarea.val().replace(/ଆପେଲ୍‌/g," ଆପଲ"));
textarea.val(textarea.val().replace(/‌େହା/g," ହୋ"));
textarea.val(textarea.val().replace(/‌ୟୋ/g,"ୟୋ"));
textarea.val(textarea.val().replace(/ଶାନ୍ତ୍ରୀ/g,"ଶାସ୍ତ୍ରୀ"));
textarea.val(textarea.val().replace(/ଶାନ୍ତ୍ରୀ/g,"ଶାସ୍ତ୍ରୀ"));
textarea.val(textarea.val().replace(/‌ଅା/g,"ଆ"));
textarea.val(textarea.val().replace(/ଡ଼ାଉନ/g,"ଡାଉନ"));
textarea.val(textarea.val().replace(/ଖଣ୍ତ/g,"ଖଣ୍ଡ"));
textarea.val(textarea.val().replace(/ଘଡା/g,"ଘଡ଼ା"));
textarea.val(textarea.val().replace(/ସେଆର/g," ସେୟାର"));
textarea.val(textarea.val().replace(/ଗରିଫ/g," ଗିରଫ"));
textarea.val(textarea.val().replace(/ଡ଼ାକ୍ତର/g," ଡାକ୍ତର"));
textarea.val(textarea.val().replace(/ସମତେ/g," ସମେତ"));
textarea.val(textarea.val().replace(/ଅ‌ା/g,"ଆ"));
textarea.val(textarea.val().replace(/ପ‌ାରା/g,"ପାରା"));
textarea.val(textarea.val().replace(/ଦକ୍ଷିଣ‌େର/g,"ଦକ୍ଷିଣରେ"));
textarea.val(textarea.val().replace(/ଅପରାହ୍ନ/g," ଅପରାହ୍ଣ"));
textarea.val(textarea.val().replace(/ମନସ୍ତ/g," ମନସ୍ଥ"));
textarea.val(textarea.val().replace(/ଆଡେ/g," ଆଡ଼େ"));
textarea.val(textarea.val().replace(/ଗାଧେଇବା/g," ଗାଧୋଇବା"));
textarea.val(textarea.val().replace(/କାନାଡା/g," କାନାଡ଼ା"));
textarea.val(textarea.val().replace(/ଗୁଡାଏ/g," ଗୁଡ଼ାଏ"));
textarea.val(textarea.val().replace(/ବୁଡାଇ/g," ବୁଡ଼ାଇ"));
textarea.val(textarea.val().replace(/ଏକ୍‌ସ୍‌ଚେଞ୍ଚ୍‌/g," ଏକ୍‌ସଚେଞ୍ଜ"));
textarea.val(textarea.val().replace(/ହଜାର/g," ହଜାର"));
textarea.val(textarea.val().replace(/ଜଣ/g," ଜଣ"));
textarea.val(textarea.val().replace(/ସମୟେରେ/g," ସମୟରେ"));
textarea.val(textarea.val().replace(/ବଦ୍ୟୁତ/g," ବିଦ୍ୟୁତ୍‌"));
textarea.val(textarea.val().replace(/କାର୍ଯ୍ୟକ୍ରମ‌େର/g," କାର୍ଯ୍ୟକ୍ରମରେ"));
textarea.val(textarea.val().replace(/ଳଜ୍ଜା/g," ଲଜ୍ଜା"));
textarea.val(textarea.val().replace(/ଳଜ୍ଜା/g," ଲଜ୍ଜା"));
textarea.val(textarea.val().replace(/ଠିକ/g," ଠିକ୍‌"));
textarea.val(textarea.val().replace(/ବିମାନବନ୍ଦର/g," ବିମାନ ବନ୍ଦର"));
textarea.val(textarea.val().replace(/କ‌େଣ୍ଟ୍ରାଲ୍‌/g," କଣ୍ଟ୍ରୋଲ"));
textarea.val(textarea.val().replace(/ଷଦ୍‌/g,"ଷଦ"));
textarea.val(textarea.val().replace(/ଢ଼ିପ/g,"ଢିପ"));
textarea.val(textarea.val().replace(/ଯବନା/g,"ଯବାନ"));
textarea.val(textarea.val().replace(/କ୍ଲାନ୍ତି/g,"କ୍ଳାନ୍ତି"));
textarea.val(textarea.val().replace(/ପ୍ରତିହିତ/g,"ପ୍ରତିହତ"));
textarea.val(textarea.val().replace(/ଣ୍ତ/g,"ଣ୍ଡ"));
textarea.val(textarea.val().replace(/େସ୍ରା/g,"ସ୍ରୋ"));
textarea.val(textarea.val().replace(/ଅଫିସର୍/g,"ଅଫିସର"));
textarea.val(textarea.val().replace(/ଚାହୁଛନ୍ତି/g,"ଚାହୁଁଛନ୍ତି"));
textarea.val(textarea.val().replace(/ସୁବାଷ/g,"ସୁବାସ"));
textarea.val(textarea.val().replace(/ଯୋଡା/g,"ଯୋଡ଼ା"));
textarea.val(textarea.val().replace(/ପ୍ରଜୁଯ୍ୟ/g,"ପ୍ରଯୁଜ୍ୟ"));
textarea.val(textarea.val().replace(/ଜ୍ବାର/g,"ଜ୍ବର"));
textarea.val(textarea.val().replace(/ଜ୍ୱାର/g,"ଜ୍ବର"));
textarea.val(textarea.val().replace(/ମେଢ/g,"ମେଢ଼"));
textarea.val(textarea.val().replace(/ଚାକରି/g,"ଚାକିରି"));
textarea.val(textarea.val().replace(/ଦୁଖଃ/g,"ଦୁଃଖ"));
textarea.val(textarea.val().replace(/ଆକ୍‌/g,"ଆକ"));
textarea.val(textarea.val().replace(/ଅହମଦ୍/g,"ଅହମ୍ମଦ"));
textarea.val(textarea.val().replace(/ଜନେକ/g,"ଜନୈକ"));
textarea.val(textarea.val().replace(/କ୍ଷୁର୍ଣ୍ଣ/g,"କ୍ଷୁଣ୍ଣ"));
textarea.val(textarea.val().replace(/କ୍ଷୂର୍ଣ୍ଣ/g,"କ୍ଷୁଣ୍ଣ"));
textarea.val(textarea.val().replace(/କଁଇ/g,"କଇଁ"));
textarea.val(textarea.val().replace(/ମର୍ଟମ୍‌/g,"ମୋର୍ଟମ"));
textarea.val(textarea.val().replace(/ଆର୍‍/g,"ଆର"));
textarea.val(textarea.val().replace(/ଅନ୍‍ଲାଇନ୍‍/g,"ଅନ୍‌ଲାଇନ୍‌"));
textarea.val(textarea.val().replace(/ଯୋଡି/g,"ଯୋଡ଼ି"));
textarea.val(textarea.val().replace(/ସମ‌େସ୍ତ/g,"ସମସ୍ତେ"));
textarea.val(textarea.val().replace(/ମେଡିକାଲ୍‌/g,"ମେଡ଼ିକାଲ"));
textarea.val(textarea.val().replace(/େ‌/g,""));
textarea.val(textarea.val().replace(/ସି˚/g,"ସିଂ"));
textarea.val(textarea.val().replace(/ପରର୍ବତୀ/g,"ପରବର୍ତ୍ତୀ"));
textarea.val(textarea.val().replace(/ଥିନ୍‍/g,"ଥିନ"));
textarea.val(textarea.val().replace(/ସନ୍‌/g,"ସନ"));
textarea.val(textarea.val().replace(/ଢ଼ୋ/g,"ଢୋ"));
textarea.val(textarea.val().replace(/ବ୍‌/g,"ବ"));
textarea.val(textarea.val().replace(/କ୍‌/g,"କ"));
textarea.val(textarea.val().replace(/ଶଶ୍ମାନ/g,"ଶ୍ମଶାନ"));
textarea.val(textarea.val().replace(/ସ୍‌/g,"ସ"));
textarea.val(textarea.val().replace(/ଅବଜର/g,"ଅବ୍‌ଜର"));
textarea.val(textarea.val().replace(/ଉଡା/g,"ଉଡ଼ା"));
textarea.val(textarea.val().replace(/ମେଡିକାଲ/g,"ମେଡ଼ିକାଲ"));
textarea.val(textarea.val().replace(/ଶୋଡ଼ଷ/g,"ଷୋଡ଼ଶ"));
textarea.val(textarea.val().replace(/ହାଇଦ୍ରାବାଦ୍‌/g,"ହାଇଦ୍ରାବାଦ"));
textarea.val(textarea.val().replace(/ଦ୍ୱିତିୟ/g,"ଦ୍ବିତୀୟ"));
textarea.val(textarea.val().replace(/ଗୋଡ/g,"ଗୋଡ଼"));
textarea.val(textarea.val().replace(/ନାଲ୍‌/g,"ନାଲ"));
textarea.val(textarea.val().replace(/ନାଲ୍‌/g,"ନାଲ"));
textarea.val(textarea.val().replace(/ପଲସର୍/g,"ପଲ୍‌ସର"));
textarea.val(textarea.val().replace(/ଗଢି/g,"ଗଢ଼ି"));
textarea.val(textarea.val().replace(/କାର୍ଯ୍ୟକରୀ/g,"କାର୍ଯ୍ୟକାରୀ"));
textarea.val(textarea.val().replace(/ଣ୍ଡ୍‌/g,"ଣ୍ଡ"));
textarea.val(textarea.val().replace(/ଆନ୍‌ଜିଓଗ୍ରାମ/g,"ଆଞ୍ଜିଓଗ୍ରାମ୍‌"));
textarea.val(textarea.val().replace(/ଅଭିଯାଗ/g,"ଅଭିଯୋଗ"));
textarea.val(textarea.val().replace(/ଷ୍ଟ୍‌/g,"ଷ୍ଟ"));
textarea.val(textarea.val().replace(/ଷ୍ଟ୍‌/g,"ଷ୍ଟ"));
textarea.val(textarea.val().replace(/କଡ/g,"କଡ଼"));
textarea.val(textarea.val().replace(/ଟେକନିସିଆନ୍/g,"ଟେକ୍‌ନିସିଆନ")); 
textarea.val(textarea.val().replace(/ବଂଚି/g,"ବଞ୍ଚି"));
textarea.val(textarea.val().replace(/ମାଢି/g,"ମାଢ଼ି"));
textarea.val(textarea.val().replace(/ଣ୍ଟ୍/g,"ଣ୍ଟ"));
textarea.val(textarea.val().replace(/କ୍ଟ୍‌/g,"କ୍ଟ"));
textarea.val(textarea.val().replace(/ଚାହିଲେ/g,"ଚାହିଁଲେ"));
textarea.val(textarea.val().replace(/ଫେରେନ୍ସି/g,"ଫେରନସିଂ"));
textarea.val(textarea.val().replace(/ଭ୍‌/g,"ଭ"));
textarea.val(textarea.val().replace(/ଲିଫ୍‌ଟ୍‌/g,"ଲିଫ୍‌ଟ"));
textarea.val(textarea.val().replace(/ଦେବାଦେବୀ/g,"ଦେବଦେବୀ"));
textarea.val(textarea.val().replace(/ଉଡେଇ/g,"ଉଡ଼େଇ"));
textarea.val(textarea.val().replace(/ଚେକ/g,"ଚେକ୍‌"));
textarea.val(textarea.val().replace(/କାର୍ଡ/g,"କାର୍ଡ"));
textarea.val(textarea.val().replace(/ସମାରିକ/g,"ସାମରିକ"));
textarea.val(textarea.val().replace(/ଖାନଙ୍କୁ/g,"ଖାନ୍‌ଙ୍କୁ"));
textarea.val(textarea.val().replace(/ସବୁନ୍‌/g,"ସାବୁନ"));
textarea.val(textarea.val().replace(/ପରିଶ୍ରା/g,"ପରିସ୍ରା "));
textarea.val(textarea.val().replace(/ଏଡା/g,"ଏଡ଼ା"));
textarea.val(textarea.val().replace(/ପାଟ୍‌ନା/g,"ପାଟନା"));
textarea.val(textarea.val().replace(/ସେଲଟର/g,"ସେଲ୍‌ଟର"));
textarea.val(textarea.val().replace(/ଉଜୁଡା/g,"ଉଜୁଡ଼ା"));
textarea.val(textarea.val().replace(/ଫ୍ୟାନ/g,"ଫ୍ୟାନ୍‌"));
textarea.val(textarea.val().replace(/ଶୀଷର୍କ/g,"ଶୀର୍ଷକ‌"));
textarea.val(textarea.val().replace(/କମେଡି/g,"କମେଡ଼ି"));
textarea.val(textarea.val().replace(/ତଡ/g,"ତଡ଼"));
textarea.val(textarea.val().replace(/କହୁନ୍ତି/g,"କୁହନ୍ତି"));
textarea.val(textarea.val().replace(/ନିଧୁର୍ମ/g,"ନିର୍ଧୁମ"));
textarea.val(textarea.val().replace(/ମେକଅପ/g,"ମେକ୍‌ଅପ"));
textarea.val(textarea.val().replace(/ଏଡେ/g,"ଏଡ଼େ"));
textarea.val(textarea.val().replace(/ଏଡା/g,"ଏଡ଼ା"));
textarea.val(textarea.val().replace(/ପେନସ/g,"ପେନ୍‌ସ"));
textarea.val(textarea.val().replace(/ଗୋଲକୁ/g,"ଗୋଲ୍‌କୁ"));
textarea.val(textarea.val().replace(/ଗୋଲରେ/g,"ଗୋଲ୍‌ରେ")); 
textarea.val(textarea.val().replace(/ଜାକସନ/g,"ଜ୍ୟାକ୍‌ସନ୍‌"));
textarea.val(textarea.val().replace(/ହାଡ/g,"ହାଡ଼"));
textarea.val(textarea.val().replace(/କ୍ୟାନସର/g,"କ୍ୟାନ୍‌ସର"));
textarea.val(textarea.val().replace(/ଲୁଟପାଟ/g,"ଲୁଟ୍‌ପାଟ୍‌"));
textarea.val(textarea.val().replace(/ଚଢି/g,"ଚଢ଼ି"));
textarea.val(textarea.val().replace(/ଓଭର‌୍‌/g,"ଓଭର"));
textarea.val(textarea.val().replace(/ମେସରେ/g," ମେସ୍‌ରେ"));
textarea.val(textarea.val().replace(/ମେସକୁ/g," ମେସ୍‌କୁ"));
textarea.val(textarea.val().replace(/ଗାଡ/g,"ଗାଡ଼"));
textarea.val(textarea.val().replace(/ଡ଼ିଏସ/g,"ଡିଏସ୍‌"));
textarea.val(textarea.val().replace(/ଗାର୍‌ନେଟ୍‌/g,"ଗାରନେଟ୍‌"));
textarea.val(textarea.val().replace(/ଡେଣ୍ଟାଲ୍‌/g,"ଡେଣ୍ଟାଲ"));
textarea.val(textarea.val().replace(/ସଡକ/g,"ସଡ଼କ"));
textarea.val(textarea.val().replace(/ଦେବାତାଙ୍କୁ/g,"ଦେବତାଙ୍କୁ"));
textarea.val(textarea.val().replace(/ମେଲବର୍ଣ୍ଣ/g,"ମେଲ୍‌ବର୍ଣ୍ଣ"));
textarea.val(textarea.val().replace(/ଜାଡ/g,"ଜାଡ଼"));
textarea.val(textarea.val().replace(/ଗୌଡ/g,"ଗୌଡ଼"));
textarea.val(textarea.val().replace(/ଆଡ଼୍ଡ଼ା/g,"ଆଡ୍ଡା"));
textarea.val(textarea.val().replace(/ରେଡ଼୍/g,"ରେଡ୍‌"));
textarea.val(textarea.val().replace(/ଅଜର୍ନ/g,"ଅର୍ଜନ"));
textarea.val(textarea.val().replace(/ଚକଚକ/g,"ଚକ୍‌ଚକ୍‌"));
textarea.val(textarea.val().replace(/ବଡ/g,"ବଡ଼"));
textarea.val(textarea.val().replace(/ପ୍ରତ୍ୟେକ୍ଷ/g,"ପ୍ରତ୍ୟକ୍ଷ"));
textarea.val(textarea.val().replace(/ଡ଼ିଏଫଓ/g,"ଡିଏଫଓ"));
textarea.val(textarea.val().replace(/ହଟାତ୍‌/g,"ହଠାତ୍‌"));
textarea.val(textarea.val().replace(/କିମିଟି/g,"କମିଟି"));
textarea.val(textarea.val().replace(/ନିର୍ଷ୍କସ/g,"ନିଷ୍କର୍ସ"));
textarea.val(textarea.val().replace(/ନବଗଜାତକ/g,"ନବଜାତକ"));
textarea.val(textarea.val().replace(/ତେଜ୍ବସି/g,"ତେଜସ୍ବୀ"));
textarea.val(textarea.val().replace(/ତେଜ୍ବସୀ/g,"ତେଜସ୍ବୀ"));
textarea.val(textarea.val().replace(/ସହେଯାଗ/g,"ସହଯୋଗ"));
textarea.val(textarea.val().replace(/ପ୍ୟାନସି/g,"ଫ୍ୟାନ୍ସି"));
textarea.val(textarea.val().replace(/କଡ଼/g,"କଡ଼"));
textarea.val(textarea.val().replace(/ସ୍ୱା/g,"ସ୍ବା"));
textarea.val(textarea.val().replace(/ଡ଼/g,"ଡ଼"));
textarea.val(textarea.val().replace(/ଡ଼଼ି/g,"ଡ଼ି"));
textarea.val(textarea.val().replace(/ଡ଼଼ା/g,"ଡ଼ା"));
textarea.val(textarea.val().replace(/ସ୍ୱ/g,"ସ୍ବ"));
textarea.val(textarea.val().replace(/ଢ଼/g,"ଢ଼"));
textarea.val(textarea.val().replace(/ତ୍ତ୍ୱ/g,"ତ୍ତ୍ବ"));
textarea.val(textarea.val().replace(/ଷଡ/g,"ଷଡ଼"));
textarea.val(textarea.val().replace(/ଶ୍ୱ/g,"ଶ୍ବ"));
textarea.val(textarea.val().replace(/ବାରିକେଡ/g,"ବ୍ୟାରିକେଡ୍‌"));
textarea.val(textarea.val().replace(/ଭିଡ଼଼/g,"ଭିଡ଼"));
textarea.val(textarea.val().replace(/ବିରିଡି/g,"ବିରିଡ଼ି"));
textarea.val(textarea.val().replace(/ଣ୍ଟ/g,"ଣ୍ଟ"));
textarea.val(textarea.val().replace(/ଣ୍ଟୋ/g,"ଣ୍ଟୋ"));
textarea.val(textarea.val().replace(/ଢ଼ା/g,"ଢ଼ା"));
textarea.val(textarea.val().replace(/ଚ୍‍/g,"ଚ୍‌"));
textarea.val(textarea.val().replace(/ଦୁରାବସ୍ତା/g,"ଦୁରବସ୍ଥା"));
textarea.val(textarea.val().replace(/ଦୁରାବସ୍ଥା/g,"ଦୁରବସ୍ଥା"));
textarea.val(textarea.val().replace(/ପଇଁନ୍ତରା/g,"ପଇନ୍ତରା"));
textarea.val(textarea.val().replace(/ମଲିକ୍/g,"ମଲ୍ଲିକ"));
textarea.val(textarea.val().replace(/ହଠାତ୍‍/g,"ହଠାତ୍‌"));
textarea.val(textarea.val().replace(/ମ୍‍/g,"ମ୍‌"));
textarea.val(textarea.val().replace(/ଦାଳଇ/g,"ଦଳାଇ"));
textarea.val(textarea.val().replace(/ହୁଡା/g,"ହୁଡ଼ା"));
textarea.val(textarea.val().replace(/ରଡି/g,"ରଡ଼ି"));
textarea.val(textarea.val().replace(/ସ୍ବଗର୍ତ/g,"ସ୍ବର୍ଗତ"));
textarea.val(textarea.val().replace(/ତ୍ୱ/g,"ତ୍ବ"));
textarea.val(textarea.val().replace(/ସୌ/g,"ସୌ"));
textarea.val(textarea.val().replace(/ସର୍ବେସ୍ବର/g,"ସର୍ବେଶ୍ବର"));


    });
});